<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GameRuntime</RootNamespace>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameFramework\GameFramework.csproj" />
    <ProjectReference Include="..\GameGenerated\GameGenerated.csproj" />
    <ProjectReference Include="..\GameLogic\GameLogic.csproj" />
  </ItemGroup>

</Project>
