// <auto-generated>
// 此文件由工具自动生成，请勿手动修改
// </auto-generated>

namespace GameFramework.Network.Protobuf
{
    /// <summary>
    /// 协议消息ID枚举
    /// </summary>
    public enum EProtocol : ushort
    {

        // ---- game.proto ----
        HeartbeatReq = 1000,
        HeartbeatRes = 1001,
        ErrorNotify = 1002,
        LoginReq = 1003,
        LoginRes = 1004,
        PlayerInfo = 1005,
        ItemInfo = 1006,
        PlayerDataSync = 1007,
    }
}