// <auto-generated>
// 此文件由工具自动生成，请勿手动修改
// </auto-generated>

using GameFramework.Network.Protobuf;
using GameLogic.Network;

namespace GameLogic.Network
{
    /// <summary>
    /// 消息处理器注册器（自动生成）
    /// </summary>
    public static class MessageRegistration
    {
        public static void RegisterAll(GameFramework.Network.NetworkManager network)
        {
            // ---- game.proto ----
            // network.RegisterHandler<HeartbeatReq>((ushort)EProtocol.HeartbeatReq, OnHeartbeatHandler);
            // network.RegisterHandler<HeartbeatRes>((ushort)EProtocol.HeartbeatRes, OnHeartbeatHandler);
            // network.RegisterHandler<ErrorNotify>((ushort)EProtocol.ErrorNotify, OnErrorNotify);
            // network.RegisterHandler<LoginReq>((ushort)EProtocol.LoginReq, OnLoginHandler);
            // network.RegisterHandler<LoginRes>((ushort)EProtocol.LoginRes, OnLoginHandler);
            // network.RegisterHandler<PlayerInfo>((ushort)EProtocol.PlayerInfo, OnPlayerInfo);
            // network.RegisterHandler<ItemInfo>((ushort)EProtocol.ItemInfo, OnItemInfo);
            // network.RegisterHandler<PlayerDataSync>((ushort)EProtocol.PlayerDataSync, OnPlayerDataSync);
        }
    }
}