#!/usr/bin/env python3
"""
Protobuf 协议 -> C# 代码生成器。

功能：
1. 扫描 .proto 文件提取消息名称
2. 生成消息 ID 枚举 (EProtocol.cs)
3. 生成消息处理注册代码

消息ID分配规则：
- 使用 proto 文件中消息定义的顺序分配ID
- 从 1000 开始，每消息间隔 +1

用法：
    python proto_codegen.py --proto-dir ../proto/ --output-dir ../client/GameFramework/Network/Protobuf/
"""

import argparse
import os
import re
import sys
from typing import Dict, List, Set


def parse_proto_file(filepath: str) -> List[str]:
    """解析 .proto 文件，返回消息类型名称列表"""
    messages: List[str] = []
    package = ""
    proto_pattern = re.compile(r"^\s*package\s+(\S+)\s*;")
    message_pattern = re.compile(r"^\s*message\s+(\w+)")

    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            m = message_pattern.match(line)
            if m:
                messages.append(m.group(1))

    return messages


def scan_proto_directory(proto_dir: str) -> Dict[str, List[str]]:
    """扫描目录下所有 .proto 文件，返回 文件名->消息列表 的映射"""
    result: Dict[str, List[str]] = {}

    if not os.path.isdir(proto_dir):
        print(f"[WARN] Proto 目录不存在: {proto_dir}")
        return result

    for filename in sorted(os.listdir(proto_dir)):
        if not filename.endswith(".proto"):
            continue
        filepath = os.path.join(proto_dir, filename)
        messages = parse_proto_file(filepath)
        if messages:
            result[filename] = messages

    return result


def generate_protocol_enum(proto_map: Dict[str, List[str]], start_id: int = 1000) -> str:
    """生成消息ID枚举 EProtocol.cs"""
    lines = [
        "// <auto-generated>",
        "// 此文件由工具自动生成，请勿手动修改",
        "// </auto-generated>",
        "",
        "namespace GameFramework.Network.Protobuf",
        "{",
        "    /// <summary>",
        "    /// 协议消息ID枚举",
        "    /// </summary>",
        "    public enum EProtocol : ushort",
        "    {",
    ]

    current_id = start_id
    for filename, messages in proto_map.items():
        lines.append("")
        lines.append(f"        // ---- {filename} ----")
        for msg in messages:
            # 生成枚举项: MsgName = 1000,
            enum_name = msg
            lines.append(f"        {enum_name} = {current_id},")
            current_id += 1

    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


def generate_handler_registration(proto_map: Dict[str, List[str]], namespace: str = "GameLogic.Network") -> str:
    """生成消息处理注册代码"""
    lines = [
        "// <auto-generated>",
        "// 此文件由工具自动生成，请勿手动修改",
        "// </auto-generated>",
        "",
        "using GameFramework.Network.Protobuf;",
        f"using {namespace};",
        "",
        f"namespace {namespace}",
        "{",
        "    /// <summary>",
        "    /// 消息处理器注册器（自动生成）",
        "    /// </summary>",
        "    public static class MessageRegistration",
        "    {",
        "        public static void RegisterAll(GameFramework.Network.NetworkManager network)",
        "        {",
    ]

    for filename, messages in proto_map.items():
        lines.append(f"            // ---- {filename} ----")
        for msg in messages:
            req_name = msg
            res_name = msg  # might have Req/Res patterns

            # Generate registration code, using naming convention Req/Res for handler names
            handler_name = msg.replace("Req", "Handler").replace("Res", "Handler")
            lines.append(f"            // network.RegisterHandler<{req_name}>((ushort)EProtocol.{msg}, On{handler_name});")

    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


def generate_merge_script(proto_map: Dict[str, List[str]]) -> str:
    """生成合并proto的批处理脚本（用于 protoc 编译）"""
    lines = [
        "#!/bin/bash",
        "# Proto编译脚本 - 使用 protoc 生成C#代码",
        f"# 在 {os.path.dirname(os.path.abspath(__file__))} 目录下运行",
        "",
        "PROTO_DIR=\"../proto\"",
        "OUTPUT_DIR=\"../../client/GameFramework/Network/Protobuf/Generated\"",
        "",
        "mkdir -p $OUTPUT_DIR",
        "",
    ]

    for filename in sorted(proto_map.keys()):
        lines.append(f"# protoc --proto_path=$PROTO_DIR --csharp_out=$OUTPUT_DIR $PROTO_DIR/{filename}")

    lines.append("")
    lines.append("echo \"Proto compilation complete. Output: $OUTPUT_DIR\"")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Proto -> C# 代码生成器")
    parser.add_argument("--proto-dir", "-p", default="../proto", help="proto 文件目录")
    parser.add_argument("--output-dir", "-o", default="./Output", help="输出目录")
    parser.add_argument("--start-id", type=int, default=1000, help="起始消息ID")

    args = parser.parse_args()

    # 扫描 proto
    proto_map = scan_proto_directory(args.proto_dir)

    if not proto_map:
        print("[WARN] 未找到任何 .proto 文件")
        # 即使没有proto也生成一个空的枚举文件
        proto_map = {"game.proto": ["HeartbeatReq", "HeartbeatRes", "LoginReq", "LoginRes", "PlayerInfo", "ItemInfo"]}

    # 生成文件
    os.makedirs(args.output_dir, exist_ok=True)

    # 1. EProtocol.cs
    enum_code = generate_protocol_enum(proto_map, args.start_id)
    enum_file = os.path.join(args.output_dir, "EProtocol.cs")
    with open(enum_file, "w", encoding="utf-8") as f:
        f.write(enum_code)
    print(f"[OK] 生成: {enum_file}")

    # 2. MessageRegistration.cs
    reg_code = generate_handler_registration(proto_map)
    reg_file = os.path.join(args.output_dir, "MessageRegistration.cs")
    with open(reg_file, "w", encoding="utf-8") as f:
        f.write(reg_code)
    print(f"[OK] 生成: {reg_file}")

    print(f"\n总计: {sum(len(v) for v in proto_map.values())} 条消息")


if __name__ == "__main__":
    main()
