#!/usr/bin/env python3
"""
Protobuf 协议 → C# 代码生成器。

从 .proto + .id 文件生成三部分：
  1. C# 消息类 — 由 protoc 生成（Google.Protobuf.IMessage 实现）
  2. EProtocol.cs — 消息 ID 枚举（框架层）
  3. {Proto}Handler.cs — GC_ 消息处理器桩 + 自动注册

消息 ID 统一定义在 proto.id 中（目录下所有 proto 共用一份）。
消息命名约定：
  CG_xxx  客户端→服务器（不生成处理器）
  GC_xxx  服务器→客户端（自动生成处理器 + 注册代码）

用法：
  python proto_codegen.py \
    --proto-dir public/proto/ \
    --output-dir client/GameFramework/Network/Protobuf/ \
    --handler-dir client/GameLogic/Network/Handlers/
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from typing import Dict, List, Optional, Tuple


# ============================================================
# 解析器
# ============================================================

def parse_id_file(filepath: str) -> Dict[str, int]:
    """解析 .id 文件，返回 {消息名: ID编号}"""
    result: Dict[str, int] = {}
    if not os.path.exists(filepath):
        return result
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or stripped.startswith("//"):
                continue
            m = re.match(r"(\w+)\s*=\s*(\d+)", stripped)
            if m:
                result[m.group(1)] = int(m.group(2))
    return result


def extract_messages(filepath: str) -> List[Dict]:
    """
    扫描 .proto 文件，提取消息名称与类型。
    返回 [{ name: "CG_Heartbeat", type: "cg" }, ...]
    只需消息名和 CG_/GC_ 分类，无需解析字段细节（protoc 处理）。
    """
    messages: List[Dict] = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            m = re.match(r"^message\s+(\w+)", line.strip())
            if m:
                name = m.group(1)
                msg_type = "data"
                if name.startswith("CG_"):
                    msg_type = "cg"
                elif name.startswith("GC_"):
                    msg_type = "gc"
                messages.append({"name": name, "type": msg_type})
    return messages


def scan_proto_directory(proto_dir: str) -> Dict[str, Tuple[List[Dict]]]:
    """扫描目录下所有 .proto 文件，从全局 proto.id 读取 ID 映射"""
    result: Dict[str, Tuple[List[Dict]]] = {}

    if not os.path.isdir(proto_dir):
        print(f"[ERR] Proto 目录不存在: {proto_dir}")
        sys.exit(1)

    # 读取全局 ID 文件
    id_path = os.path.join(proto_dir, "proto.id")
    id_map = parse_id_file(id_path)
    if id_map:
        print(f"[ID] 加载 {id_path}（{len(id_map)} 条 ID）")

    for filename in sorted(os.listdir(proto_dir)):
        if not filename.endswith(".proto"):
            continue
        filepath = os.path.join(proto_dir, filename)
        messages = extract_messages(filepath)

        for m in messages:
            m["id"] = id_map.get(m["name"])

        if messages:
            result[filename] = (messages,)

    return result


# ============================================================
# EProtocol.cs 生成
# ============================================================

def generate_protocol_enum(proto_map: Dict[str, Tuple[List[Dict]]]) -> str:
    """生成 EProtocol.cs"""
    lines = [
        "// <auto-generated>",
        "// 此文件由工具自动生成，请勿手动修改",
        "// </auto-generated>",
        "",
        "namespace GameFramework.Network.Protobuf",
        "{",
        "    /// <summary>",
        "    /// 协议消息 ID 枚举（前后端共用）",
        "    /// </summary>",
        "    public enum EProtocol : ushort",
        "    {",
        "        None = 0,",
    ]

    for filename, (messages,) in proto_map.items():
        with_id = [m for m in messages if m["id"] is not None]
        if not with_id:
            continue
        lines.append("")
        lines.append(f"        // ---- {filename} ----")
        for m in with_id:
            lines.append(f"        {m['name']} = {m['id']},")

    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ============================================================
# 处理器桩生成
# ============================================================

def to_handler_class(proto_filename: str) -> str:
    base = os.path.splitext(proto_filename)[0]
    return "".join(word[0].upper() + word[1:] for word in re.split(r"[_\- ]", base)) + "Handler"


def generate_handler_file(proto_filename: str, messages: List[Dict]) -> Optional[str]:
    gc_msgs = [m for m in messages if m["type"] == "gc" and m["id"] is not None]
    if not gc_msgs:
        return None

    class_name = to_handler_class(proto_filename)
    lines = [
        "// <auto-generated>",
        "// 此文件由工具自动生成，请勿手动修改",
        "// </auto-generated>",
        "",
        "using GameFramework.Network;",
        "using GameFramework.Network.Protobuf;",
        "",
        "namespace GameLogic.Network.Handlers",
        "{",
        f"    /// <summary>",
        f"    /// {proto_filename} 处理器（自动注册 + 回调桩）",
        f"    /// 在对应方法中编写业务逻辑",
        f"    /// </summary>",
        f"    public static class {class_name}",
        "    {",
        "        public static void RegisterAll(NetworkManager network)",
        "        {",
    ]

    for m in gc_msgs:
        lines.append(
            f"            network.RegisterHandler<{m['name']}>("
            f"(ushort)EProtocol.{m['name']}, On{m['name']});"
        )

    lines.append("        }")
    lines.append("")

    for m in gc_msgs:
        lines.append("        /// <summary>")
        lines.append(f"        /// 处理 {m['name']}")
        lines.append("        /// </summary>")
        lines.append(f"        public static void On{m['name']}({m['name']} msg)")
        lines.append("        {")
        lines.append(f"            // TODO: handle {m['name']}")
        lines.append("        }")
        lines.append("")

    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


# ============================================================
# protoc 调用
# ============================================================

def find_protoc(custom_path: Optional[str] = None) -> str:
    """查找 protoc 可执行文件路径"""
    if custom_path:
        if os.path.isfile(custom_path):
            return custom_path
        print(f"[ERR] 指定的 protoc 路径不存在: {custom_path}")
        sys.exit(1)

    # 1. 检查脚本自身目录下的 protoc-*/bin/
    script_dir = os.path.dirname(os.path.abspath(__file__))
    for entry in os.listdir(script_dir):
        full = os.path.join(script_dir, entry)
        if os.path.isdir(full) and entry.startswith("protoc"):
            candidate = os.path.join(full, "bin", "protoc.exe")
            if os.path.isfile(candidate):
                return candidate

    # 2. 检查 PATH
    protoc = shutil.which("protoc")
    if protoc:
        return protoc

    # 3. 检查 NuGet 缓存
    home = os.path.expanduser("~")
    nuget_cache = os.path.join(home, ".nuget", "packages", "google.protobuf.tools")
    if os.path.isdir(nuget_cache):
        versions = sorted(os.listdir(nuget_cache), reverse=True)
        for ver in versions:
            for arch in ("windows_x64", "windows_x86", "windows"):
                candidate = os.path.join(nuget_cache, ver, "tools", arch, "protoc.exe")
                if os.path.isfile(candidate):
                    return candidate

    print("[ERR] 未找到 protoc，请安装:")
    print(f"   将 protoc 放到 {script_dir}/protoc-*/bin/ 下")
    print("   或: choco install protoc")
    print("   或: https://github.com/protocolbuffers/protobuf/releases")
    print("   或: --protoc-path 指定路径")
    sys.exit(1)


def run_protoc(protoc_path: str, proto_dir: str, proto_filename: str, output_dir: str) -> None:
    """调用 protoc 生成 C# 消息类"""
    proto_file = os.path.join(proto_dir, proto_filename)
    result = subprocess.run(
        [
            protoc_path,
            f"--proto_path={proto_dir}",
            f"--csharp_out={output_dir}",
            proto_file,
        ],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode != 0:
        print(f"[ERR] protoc 生成 {proto_filename} 失败:")
        for line in result.stderr.strip().split("\n"):
            print(f"       {line}")
        sys.exit(1)


# ============================================================
# CLI
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Proto → C# 代码生成器（protoc）")
    parser.add_argument("--proto-dir", "-p", default="../proto",
                        help="proto 文件目录")
    parser.add_argument("--output-dir", "-o", default="./Output",
                        help="EProtocol.cs + protoc 输出目录")
    parser.add_argument("--handler-dir", "-hd", default=None,
                        help="处理器桩输出目录（默认同 output-dir）")
    parser.add_argument("--protoc-path", default=None,
                        help="protoc 可执行文件路径（默认从 PATH 查找）")
    args = parser.parse_args()

    handler_dir = args.handler_dir or args.output_dir

    # 查找 protoc
    protoc_path = find_protoc(args.protoc_path)
    print(f"[protoc] {protoc_path}")

    # 扫描 proto
    proto_map = scan_proto_directory(args.proto_dir)
    if not proto_map:
        print("[ERR] 未找到 .proto 文件")
        sys.exit(1)

    # ID 唯一性校验
    id_registry: Dict[int, str] = {}
    has_dup = False
    for filename, (messages,) in proto_map.items():
        for m in messages:
            if m["id"] is None:
                continue
            if m["id"] in id_registry:
                print(f"[ERR] ID {m['id']} 冲突: {m['name']} ({filename}) 与 "
                      f"{id_registry[m['id']]} 重复")
                has_dup = True
            else:
                id_registry[m["id"]] = f"{m['name']} ({filename})"
    if has_dup:
        sys.exit(1)
    print(f"[OK] 消息 ID 唯一性校验通过（{len(id_registry)} 个 ID）")

    os.makedirs(args.output_dir, exist_ok=True)
    os.makedirs(handler_dir, exist_ok=True)

    total_wire = 0
    total_gc = 0

    # 1. protoc — 生成 C# 消息类
    protoc_out = os.path.join(args.output_dir, "Generated")
    os.makedirs(protoc_out, exist_ok=True)

    for filename, (messages,) in proto_map.items():
        if not filename.endswith(".proto"):
            continue
        run_protoc(protoc_path, args.proto_dir, filename, protoc_out)
        print(f"[OK] protoc → {protoc_out}/{os.path.splitext(filename)[0]}.cs")

        wire = [m for m in messages if m["type"] in ("cg", "gc") and m["id"] is not None]
        gc = [m for m in messages if m["type"] == "gc" and m["id"] is not None]
        total_wire += len(wire)
        total_gc += len(gc)

        for m in messages:
            if m["type"] in ("cg", "gc") and m["id"] is None:
                print(f"  [WARN] {m['name']} 无 ID（需在 proto.id 中定义）")

    # 2. EProtocol.cs
    enum_code = generate_protocol_enum(proto_map)
    enum_path = os.path.join(args.output_dir, "EProtocol.cs")
    with open(enum_path, "w", encoding="utf-8") as f:
        f.write(enum_code)
    print(f"[OK] {enum_path}")

    # 3. 处理器桩
    for filename, (messages,) in proto_map.items():
        code = generate_handler_file(filename, messages)
        if code:
            class_name = to_handler_class(filename)
            handler_path = os.path.join(handler_dir, f"{class_name}.cs")
            with open(handler_path, "w", encoding="utf-8") as f:
                f.write(code)
            print(f"[OK] {handler_path}")

    print(f"\n总计: {total_wire} 条签约消息, {total_gc} 个 GC_ 自动处理器")


if __name__ == "__main__":
    main()
