// <auto-generated>
// 此文件由工具自动生成，请勿手动修改
// </auto-generated>

using GameFramework.Network;
using GameFramework.Network.Protobuf;

namespace GameLogic.Network.Handlers
{
    /// <summary>
    /// game.proto 处理器（自动注册 + 回调桩）
    /// 在对应方法中编写业务逻辑
    /// </summary>
    public static class GameHandler
    {
        public static void RegisterAll(NetworkManager network)
        {
            network.RegisterHandler<GC_Heartbeat>((ushort)EProtocol.GC_Heartbeat, OnGC_Heartbeat);
            network.RegisterHandler<GC_ErrorNotify>((ushort)EProtocol.GC_ErrorNotify, OnGC_ErrorNotify);
            network.RegisterHandler<GC_Login>((ushort)EProtocol.GC_Login, OnGC_Login);
            network.RegisterHandler<GC_PlayerDataSync>((ushort)EProtocol.GC_PlayerDataSync, OnGC_PlayerDataSync);
        }

        /// <summary>
        /// 处理 GC_Heartbeat
        /// </summary>
        public static void OnGC_Heartbeat(GC_Heartbeat msg)
        {
            // TODO: handle GC_Heartbeat
        }

        /// <summary>
        /// 处理 GC_ErrorNotify
        /// </summary>
        public static void OnGC_ErrorNotify(GC_ErrorNotify msg)
        {
            // TODO: handle GC_ErrorNotify
        }

        /// <summary>
        /// 处理 GC_Login
        /// </summary>
        public static void OnGC_Login(GC_Login msg)
        {
            // TODO: handle GC_Login
        }

        /// <summary>
        /// 处理 GC_PlayerDataSync
        /// </summary>
        public static void OnGC_PlayerDataSync(GC_PlayerDataSync msg)
        {
            // TODO: handle GC_PlayerDataSync
        }

    }
}